name: pdpilot-eval
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - notebook
  - scikit-learn
  - nodejs
  - altair
  - matplotlib
  - optuna
  - lightgbm
  - pip
  - pip:
      - pmlb
      - pdpilot==0.5.3
