name: pdpilot-eval
channels:
  - conda-forge
dependencies:
  - python=3.10.14
  - numpy=1.26.4
  - pandas=2.2.2
  - notebook=7.2.0
  - scikit-learn=1.5.0
  - nodejs=20.12.2
  - altair-all=5.5.0
  - matplotlib=3.8.4
  - lightgbm=4.3.0
  - optuna=3.6.0
  - optuna-integration=3.6.0
  - shap=0.45.1
  - pip=24.0
  - pip:
      - pmlb==1.0.1.post3
      - pdpilot==0.6.0
